spring.application.name=payflow

spring.datasource.url=jdbc:postgresql://localhost:5432/payflow?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=payflow_user
spring.datasource.password=payflow_pass

payflow.security.api-key=payflow-secret_key-123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
